import { Activity } from './types'

export const mockActivities: Activity[] = [
  {
    id: '1',
    startDate: '2025-12-28T13:00:00Z',
    instance: 'CMTEC PVCM/CMDM',
    type: 'Painel',
    modality: 'Híbrida',
    location: 'Paço Municipal',
    participantsPF: 4,
    participantsPJ: 4,
    documents: [{ id: 'd1', category: 'Ata', name: 'Ata da Reunião' }],
    createdAt: '2025-12-01T10:00:00Z',
  },
  {
    id: '2',
    startDate: '2026-01-27T11:00:00Z',
    instance: 'CMTEC PVCM/CMDM',
    type: 'Colóquio',
    modality: 'Remota',
    location: 'Auditório PMFI',
    participantsPF: 4,
    participantsPJ: 3,
    documents: [{ id: 'd2', category: 'Relatório', name: 'Relatório Mensal' }],
    createdAt: '2025-12-02T10:00:00Z',
  },
  {
    id: '3',
    startDate: '2025-12-19T09:00:00Z',
    instance: 'CMTEC PVCM/CMDM',
    type: 'Apresentação',
    modality: 'Remota',
    location: 'Sede GGIM',
    participantsPF: 3,
    participantsPJ: 4,
    documents: [{ id: 'd3', category: 'Ofício', name: 'Ofício 123/2025' }],
    createdAt: '2025-12-03T10:00:00Z',
  },
]
