import { ActivityRecord } from './types'

export const mockActivities: ActivityRecord[] = [
  {
    id: '1',
    instance: 'CMTEC-PVCM/CMDM',
    eventType: 'Reunião Ordinária',
    modality: 'Híbrida',
    location: 'Paço Municipal',
    meetingStart: '2025-12-28T13:00:00Z',
    meetingEnd: '2025-12-28T15:00:00Z',
    hasAction: false,
    actions: [],
    participantsPF: 'João Silva; Maria Souza; Pedro Costa; Ana Lima',
    participantsPJ: 'Prefeitura; Guarda Municipal',
    documents: [{ id: 'd1', name: 'Ata da Reunião.pdf', categories: ['Ata', 'E-mail'] }],
    deliberations: 'Aprovação da pauta; Agendamento da próxima reunião',
    createdAt: '2025-12-01T10:00:00Z',
  },
  {
    id: '2',
    instance: 'Eventos Institucionais',
    eventType: 'Palestra',
    modality: 'Presencial',
    location: 'Auditório Principal',
    meetingStart: '2026-01-10T09:00:00Z',
    meetingEnd: '2026-01-10T12:00:00Z',
    hasAction: true,
    actionStart: '2026-01-10T13:00:00Z',
    actionEnd: '2026-01-10T17:00:00Z',
    actions: [{ id: 'a1', start: '2026-01-10T13:00:00Z', end: '2026-01-10T17:00:00Z' }],
    participantsPF: 'Carlos Almeida; Maria Souza; Roberto Dias',
    participantsPJ: 'Prefeitura; Polícia Civil; Corpo de Bombeiros',
    documents: [
      { id: 'd2', name: 'Apresentacao.pptx', categories: ['Outros'] },
      { id: 'd3', name: 'Fotos_Evento.jpg', categories: ['Fotos'] },
    ],
    deliberations: 'Envio de material aos participantes',
    createdAt: '2025-12-02T10:00:00Z',
  },
  {
    id: '3',
    instance: 'CMTEC-AIFU',
    eventType: 'Reunião Extraordinária',
    modality: 'Remota',
    location: 'Teams',
    meetingStart: '2026-02-15T14:00:00Z',
    meetingEnd: '2026-02-15T15:30:00Z',
    hasAction: false,
    actions: [],
    participantsPF: 'Ana Lima; Roberto Dias; João Silva',
    participantsPJ: 'Guarda Municipal; Corpo de Bombeiros',
    documents: [{ id: 'd4', name: 'Relatorio.docx', categories: ['Relatório'] }],
    deliberations: 'Revisão do planejamento',
    createdAt: '2026-02-01T10:00:00Z',
  },
]
